### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by maelle** [kehraProject/r_rdefra#13]
:wave: @cvitolo!

As seen in https://github.com/r-universe/ropensci/runs/5208774810?check_suite_focus=true via https://ropensci.r-universe.dev/ui#builds

```
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  
  == Skipped tests ===============================================================
  * Call to ukair_get_hourly_data for 1 year failed! (1)
  * Call to ukair_get_hourly_data for 2 years failed! (1)
  
  == Failed tests ================================================================
  -- Failure (test-metadata.R:23:5): Find site identification number from the UK AIR ID string. --
  x == "ABD" is not TRUE
  
  `actual`:   <NA>
  `expected`: TRUE
  
  [ FAIL 1 | WARN 0 | SKIP 2 | PASS 11 ]
``

**Comment by cvitolo** [comment]
Hi @maelle , thanks for spotting this!

It seems the UK AIR web page no longer contains the SiteID, which affects the following functions:
- `ukair_get_site_id()` (directly)
- `ukair_get_hourly_data()` (indirectly)

As a workaround, the function `ukair_get_site_id()` is now searching the cached catalogue.
However, a better solution is needed because the SiteID of new stations cannot be retrieved.

Will keep this issue open until a definitive solution is found.

**Comment by maelle** [comment]
I will archive this package as there's currently no maintainer, and it depends on retired packages. We could still unarchive it on request.
